<?php

declare(strict_types=1);

namespace Asignua\FilamentIban\Console;

use Asignua\FilamentIban\Contracts\DownloadsBanks;
use Asignua\FilamentIban\Support\BankDirectories;
use Asignua\FilamentIban\Support\Banks\FileBankDirectory;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Throwable;

class UpdateBanksCommand extends Command
{
    protected $signature = 'filament-iban:update-banks
        {country? : ISO code (UA, PL); every downloadable country when omitted}
        {--path= : Directory to write into; defaults to filament-iban.banks_path, then storage/app/filament-iban/banks}';

    protected $description = 'Download the national bank registers (NBU, NBP) used to show the bank name of an IBAN';

    public function handle(BankDirectories $directories): int
    {
        $sources = [];

        foreach ($directories->countries() as $code) {
            $directory = $directories->for($code);

            if ($directory instanceof DownloadsBanks) {
                $sources[$code] = $directory;
            }
        }

        $country = $this->argument('country');

        if (is_string($country) && $country !== '') {
            $country = strtoupper($country);

            if (!isset($sources[$country])) {
                $this->components->error("No downloadable bank register for [{$country}]. Available: ".implode(', ', array_keys($sources)));

                return self::INVALID;
            }

            $sources = [$country => $sources[$country]];
        }

        $dir = $this->targetDirectory();
        $failed = false;

        foreach ($sources as $code => $source) {
            try {
                $banks = $source->download();
            } catch (Throwable $e) {
                $this->components->error("{$code}: ".$e->getMessage());
                $failed = true;

                continue;
            }

            File::ensureDirectoryExists($dir);
            File::put($dir.'/'.strtolower($code).'.php', $this->render($source, $banks));

            if ($source instanceof FileBankDirectory) {
                $source->forget();
            }

            $this->components->info("{$code}: ".count($banks)." banks written to {$dir}/".strtolower($code).'.php');
        }

        return $failed ? self::FAILURE : self::SUCCESS;
    }

    private function targetDirectory(): string
    {
        $option = $this->option('path');

        if (is_string($option) && $option !== '') {
            return rtrim($option, '/');
        }

        $configured = config('filament-iban.banks_path');

        return is_string($configured) && $configured !== ''
            ? rtrim($configured, '/')
            : storage_path('app/filament-iban/banks');
    }

    /**
     * @param array<string, string> $banks
     */
    private function render(DownloadsBanks $source, array $banks): string
    {
        $out = "<?php\n\ndeclare(strict_types=1);\n\n";
        $out .= "// Generated by `php artisan filament-iban:update-banks`. Do not edit by hand.\n\n";
        $out .= "return [\n";
        $out .= '    \'source\' => '.var_export($source->source(), true).",\n";
        $out .= '    \'fetched_at\' => '.var_export(now()->toDateString(), true).",\n";
        $out .= "    'banks' => [\n";

        foreach ($banks as $code => $name) {
            $out .= '        '.var_export((string) $code, true).' => '.var_export($name, true).",\n";
        }

        return $out."    ],\n];\n";
    }
}
